# Generated by Django 5.0.1 on 2025-05-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_cetegoryslider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cetegoryslider',
            old_name='title2',
            new_name='bg_color',
        ),
        migrations.AddField(
            model_name='cetegoryslider',
            name='description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
