# Generated by Django 5.0.1 on 2025-05-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_rename_title2_cetegoryslider_bg_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cetegoryslider',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
